version : "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/Brussels
    ports:
      - 8191:8191
    restart: unless-stopped 

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./sonarr:/config
      - ./data/Series:/Series
    ports:
      - 8989:8989
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./deluge:/config
      - ./data/Series:/Series
      - ./data/Movies:/Movies
      - ./data/Downloads:/Downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


